### ISSUE TITLE
Enabling Private Session is not working

### ISSUE THREAD

**Issue by Lolen10** [bojanraic/spicetify-private-session#4] opened 2023-12-18 17:35 UTC
### OS Version

Windows 11 23H2 (Build 22631.2861)

### Spotify Version

1.2.26.1187.g36b715a1

### Spicetify Version

2.28.1

### Other Spicetify Extensions Installed

Extensions: Beautiful Lyrics, Adblock, Spicetify-Hide-Podcasts
Theme: Comfy (Neon)
Snippets: Hide Upgrade Button, Modern ScrollBar, Hide download button, Hide lyrics button

### Description

When starting Spotify the extension opens the Profile Menu but it doesn't enable private session.

**Comment by bojanraic** [comment] 2023-12-18 17:41
Hey, thanks for reporting this. I'm on vacation so I won't look into this for a few weeks at least. 
My suspicion is either the theme or the new Spotify version is impacting css selectors for the private session menu item selection/click.
I'll try to reproduce and see what is going on when I get back.

**Comment by Lolen10** [comment] 2023-12-18 17:44
Don't stress yourself. I hope you have a great vacation.
In the meantime, I will try to deactivate the theme and individual extensions. I'll post the results here.

**Comment by Lolen10** [comment] 2023-12-18 17:48
After I deactivated all extensions (exept Private Session), snippets and the theme, the problem still occurs.

**Comment by bojanraic** [comment] 2024-01-13 17:14
Hmmm, I am unable to reproduce this on either macOS, Linux or Windows, even with a newer version of Spicetify.
Tried your exact set of extensions/themes/snippets, and tried some other combos as well. 
The logic for identifying the Private Session button should be fairly agnostic, so I am not sure what else to try, 
Will close it as `cant-reproduce` for now. If someone else encounters it, or it breaks with a newer version of Spotify or Spicetify, I will take another look. 
Cheers

**Closed by bojanraic** 2024-01-13 17:14 UTC
